#!/usr/bin/perl
open F, "ldapsearch @ARGV|perl -MMIME::Base64 -n -00 -e 's/\n //g;s/(?<=:: )(\\S+)/decode_base64(\$1)/eg;print'|";
$R = null;
while (my $line = <F>) {
  if ($line =~ /^$/) {
    # ignore empty lines
  }
  elsif ($line =~ /^# (.*)/) {
    my @path = split(/, /, $1);

    if (scalar(@path) > 1) {
      @p = @path[1..$#path];
      $dir = join '/', reverse(@p);
      `mkdir -p $dir`;
      open $R, ">$dir/$path[0].ldif";
    }
  }
  elsif ($R) {
    print $R $line;
  }
}
close F;
